# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: s5346@程序日誌
email: ssss5346@gmail.com
description: 我是s5346，因長年都在寫iOS，漸漸想將魔手伸向後端，但因資訊量太多，所以想藉由blog記錄一下所學，幫助記憶XD
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://s5346.github.io" # the base hostname & protocol for your site
twitter_username: s5346
github_username:  s5346

# Build settings
markdown: kramdown

# 阅读处理
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"